ALT_PROTEINS = [
    {
        "protein": "SLX4IP",
        "category": "BLM restraint, replication fork protection",
        "alt_role": "Restrains BLM-dependent replication stress at ALT telomeres.",
        "vulnerability_logic": "Loss or low activity of SLX4IP may make ALT-positive cells more dependent on FANCM and vulnerable to excessive BLM-driven stress.",
        "biomarkers": ["Low SLX4IP", "High telomeric pRPA", "High pCHK1", "High APBs", "Telomere fragility"],
        "targetability": "Biomarker, not currently a mature drug target",
        "confidence": 90,
    },
    {
        "protein": "FANCM",
        "category": "Fork remodelling, ALT telomere stress control",
        "alt_role": "Limits BLM-driven replication stress at ALT telomeres.",
        "vulnerability_logic": "ALT-positive cells, especially SLX4IP-deficient cells, may be sensitive to FANCM loss or inhibition.",
        "biomarkers": ["ALT-positive", "Low SLX4IP", "High BLM", "High pRPA", "High APBs"],
        "targetability": "Emerging target",
        "confidence": 95,
    },
    {
        "protein": "BLM",
        "category": "RecQ helicase, recombination and replication fork processing",
        "alt_role": "Supports ALT-associated recombination but becomes toxic when overactive or unrestrained.",
        "vulnerability_logic": "Excessive BLM activity drives replication stress in SLX4IP/FANCM-deficient ALT cells.",
        "biomarkers": ["High BLM at telomeres", "High APBs", "High telomeric pRPA", "Hyper-ALT phenotype"],
        "targetability": "Complex, context-dependent target",
        "confidence": 90,
    },
    {
        "protein": "ATR",
        "category": "Replication-stress checkpoint kinase",
        "alt_role": "Protects ALT telomeres from unresolved replication stress.",
        "vulnerability_logic": "ALT cells with high replication stress may be sensitive to ATR inhibition.",
        "biomarkers": ["High pRPA", "High pCHK1", "Replication stress", "Telomere fragility"],
        "targetability": "Drug-targetable",
        "confidence": 92,
    },
    {
        "protein": "CHK1",
        "category": "ATR downstream checkpoint kinase",
        "alt_role": "Reflects ATR pathway activation and replication-stress signalling.",
        "vulnerability_logic": "High pCHK1 suggests checkpoint dependency.",
        "biomarkers": ["High pSer345-CHK1", "ATR activation"],
        "targetability": "Drug-targetable, but context-dependent",
        "confidence": 75,
    },
    {
        "protein": "WEE1",
        "category": "Cell-cycle checkpoint kinase",
        "alt_role": "May protect replication-stressed ALT cells from premature mitotic entry.",
        "vulnerability_logic": "ALT cells with high replication stress may be vulnerable to WEE1 inhibition.",
        "biomarkers": ["Replication stress", "G2/M checkpoint dependency", "High DNA damage"],
        "targetability": "Drug-targetable",
        "confidence": 70,
    },
    {
        "protein": "RAD52",
        "category": "Recombination, break-induced replication",
        "alt_role": "Supports ALT telomere recombination and D-loop formation.",
        "vulnerability_logic": "ALT cells with high recombination/BIR activity may depend on RAD52.",
        "biomarkers": ["High RAD52", "High POLD3", "APBs", "Telomeric DNA synthesis"],
        "targetability": "Emerging target",
        "confidence": 85,
    },
    {
        "protein": "POLD3",
        "category": "Break-induced replication DNA synthesis",
        "alt_role": "Supports ALT telomeric DNA synthesis.",
        "vulnerability_logic": "High POLD3 may indicate BIR-driven ALT dependency.",
        "biomarkers": ["High POLD3", "Telomeric EdU", "BIR signature"],
        "targetability": "Research target",
        "confidence": 82,
    },
    {
        "protein": "SMARCAL1",
        "category": "Fork remodelling translocase",
        "alt_role": "Contributes to fork remodelling and ALT telomere maintenance.",
        "vulnerability_logic": "ALT cells may show dependency on SMARCAL1, especially in certain fork-remodelling contexts.",
        "biomarkers": ["ALT-positive", "Replication fork stress", "ATRX loss"],
        "targetability": "Emerging research target",
        "confidence": 80,
    },
    {
        "protein": "EXD2",
        "category": "Nuclease, telomere processing",
        "alt_role": "Supports telomere processing and interacts genetically with BLM, DNA2, and POLD3 pathways.",
        "vulnerability_logic": "EXD2 dependency may reveal ALT cells vulnerable to combined processing defects.",
        "biomarkers": ["ALT-positive", "High BLM", "High DNA2", "High POLD3"],
        "targetability": "Research target",
        "confidence": 78,
    },
    {
        "protein": "DNA2",
        "category": "Nuclease-helicase, DNA end processing",
        "alt_role": "Processes replication and recombination intermediates.",
        "vulnerability_logic": "May interact synthetically with EXD2-related ALT stress.",
        "biomarkers": ["High resection signature", "Replication stress", "ALT-positive"],
        "targetability": "Research target",
        "confidence": 75,
    },
    {
        "protein": "BRCA1",
        "category": "Homologous recombination and fork protection",
        "alt_role": "Helps resolve replication stress and repair intermediates when FANCM is compromised.",
        "vulnerability_logic": "FANCM and BRCA1 co-loss may be synthetic lethal in ALT settings.",
        "biomarkers": ["BRCA1 loss", "FANCM dependency", "HR defect"],
        "targetability": "Biomarker and therapeutic context marker",
        "confidence": 78,
    },
    {
        "protein": "SLX4",
        "category": "DNA repair scaffold",
        "alt_role": "Works with structure-specific nucleases and interacts with ALT recombination pathways.",
        "vulnerability_logic": "RAD52 and SLX4 combined loss may compromise ALT cell viability.",
        "biomarkers": ["ALT-positive", "RAD52 dependency", "Recombination stress"],
        "targetability": "Research target",
        "confidence": 76,
    },
    {
        "protein": "MUS81",
        "category": "Structure-specific nuclease",
        "alt_role": "Processes recombination and replication intermediates.",
        "vulnerability_logic": "May influence ALT telomere processing but is not always synthetically lethal with FANCM.",
        "biomarkers": ["Recombination intermediates", "ALT stress"],
        "targetability": "Research target",
        "confidence": 62,
    },
    {
        "protein": "XPF",
        "category": "Structure-specific endonuclease",
        "alt_role": "Works with SLX4-associated DNA repair processes.",
        "vulnerability_logic": "May affect ALT telomere repair but was not strongly synthetic lethal with FANCM in the discussed study.",
        "biomarkers": ["Structure-specific repair activity"],
        "targetability": "Research target",
        "confidence": 55,
    },
    {
        "protein": "ATRX",
        "category": "Chromatin remodelling, ALT suppressor",
        "alt_role": "Loss of ATRX is strongly associated with ALT activation.",
        "vulnerability_logic": "ATRX loss helps identify ALT biology and potential ALT dependencies.",
        "biomarkers": ["ATRX loss", "ALT-positive", "Telomere length heterogeneity"],
        "targetability": "Biomarker",
        "confidence": 88,
    },
    {
        "protein": "DAXX",
        "category": "Histone chaperone, ALT-associated suppressor context",
        "alt_role": "Loss or mutation is associated with ALT in several cancers.",
        "vulnerability_logic": "DAXX loss helps identify ALT-like tumour biology.",
        "biomarkers": ["DAXX loss", "ALT-positive", "ATRX/DAXX pathway defect"],
        "targetability": "Biomarker",
        "confidence": 82,
    },
]

SYNTHETIC_LETHAL_PAIRS = [
    {
        "pair": "SLX4IP + FANCM",
        "context": "ALT-positive cancer cells",
        "effect": "Combined loss causes BLM-dependent replication stress and synthetic lethality.",
        "rescue": "BLM loss rescues the phenotype.",
        "confidence": 95,
    },
    {
        "pair": "FANCM + BLM",
        "context": "ALT-positive cancer cells",
        "effect": "Combined disruption can be lethal by collapsing ALT telomere stress control.",
        "rescue": "Context-dependent",
        "confidence": 85,
    },
    {
        "pair": "FANCM + BRCA1",
        "context": "ALT-positive cancer cells",
        "effect": "Combined loss impairs resolution of telomeric replication stress.",
        "rescue": "Not specified",
        "confidence": 82,
    },
    {
        "pair": "FANCM + SMARCAL1",
        "context": "ALT-positive fork-remodelling dependency",
        "effect": "Parallel fork-remodelling pathways can become synthetically lethal when both are disrupted.",
        "rescue": "Not specified",
        "confidence": 80,
    },
    {
        "pair": "RAD52 + SLX4",
        "context": "ALT-positive recombination-dependent telomere maintenance",
        "effect": "Combined loss impairs telomere recombination resolution and cell survival.",
        "rescue": "Not specified",
        "confidence": 78,
    },
    {
        "pair": "EXD2 + BLM",
        "context": "ALT-positive telomere processing",
        "effect": "Combined loss compromises alternative telomere-processing routes.",
        "rescue": "Not specified",
        "confidence": 77,
    },
    {
        "pair": "EXD2 + DNA2",
        "context": "ALT-positive nuclease/helicase processing",
        "effect": "Combined disruption may overload telomeric replication intermediate processing.",
        "rescue": "Not specified",
        "confidence": 75,
    },
    {
        "pair": "EXD2 + POLD3",
        "context": "ALT-positive BIR-related DNA synthesis",
        "effect": "Combined loss links telomere end processing to BIR dependency.",
        "rescue": "Not specified",
        "confidence": 75,
    },
    {
        "pair": "ALT-positive status + ATR inhibition",
        "context": "Replication-stressed ALT cells",
        "effect": "ATR inhibition may selectively kill cells with high ALT-associated replication stress.",
        "rescue": "Not specified",
        "confidence": 90,
    },
    {
        "pair": "ALT-positive status + WEE1 inhibition",
        "context": "Replication-stressed ALT cells",
        "effect": "WEE1 inhibition may force damaged ALT cells into mitosis before repair.",
        "rescue": "Not specified",
        "confidence": 70,
    },
]